name = "JacobiSVD"
uuid = "2ca068c6-2156-5cf0-8317-c67edf277a2c"
authors = ["Ralph A. Smith <smith.ralph.a@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
